spring.application.name=MusicApp
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MusicApp;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Doanbinh400915
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

#For spotify
#spring.security.oauth2.client.registration.spotify.client-id=6be4b723c77c4e39b7c6f24ee491c60c
#spring.security.oauth2.client.registration.spotify.client-secret=bf81c912807547d0ab4f6971f12ed59c
#spring.security.oauth2.client.registration.spotify.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.spotify.redirect-uri=https://localhost:8443/api/music/Home
#spring.security.oauth2.client.registration.spotify.scope=user-read-private,user-read-email
#spring.security.oauth2.client.provider.spotify.authorization-uri=https://accounts.spotify.com/authorize
#spring.security.oauth2.client.provider.spotify.token-uri=https://accounts.spotify.com/api/token
#spring.security.oauth2.client.provider.spotify.user-info-uri=https://api.spotify.com/v1/me

#ssl key-store and server port
server.port=8080
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=doanbinh400915
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=binhcloud
#
#spring.security.oauth2.client.provider.spotify.user-name-attribute=display_name
#
#server.ssl.enabled=true
#server.servlet.session.cookie.secure=true
## tells Spring to treat all incoming requests as secure
#server.forward-headers-strategy=native